# Generated by Django 4.0.2 on 2022-03-11 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivePlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(choices=[('RED', 'Red'), ('BLUE', 'Blue')], max_length=4)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.player')),
            ],
        ),
    ]
