# Generated by Django 4.0.2 on 2022-03-11 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_activeplayer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activeplayer',
            old_name='player',
            new_name='player_info',
        ),
    ]
