# Generated by Django 4.0.2 on 2022-03-12 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_player_activeplayer_player_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='codename',
            field=models.CharField(max_length=30),
        ),
    ]
