# Generated by Django 4.0.2 on 2022-03-12 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_player_codename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activeplayer',
            name='player_info',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.player'),
        ),
    ]
