# Generated by Django 4.0.2 on 2022-04-10 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_activeplayer_points_lasertagmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lasertagmessage',
            name='player1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player1_reference', to='home.activeplayer'),
        ),
        migrations.AlterField(
            model_name='lasertagmessage',
            name='player2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player2_reference', to='home.activeplayer'),
        ),
    ]
